### ISSUE TITLE
how to specify paths in 2.0.0

### ISSUE THREAD

**Issue by nitwhiz** [johnagan/clean-webpack-plugin#103]
the options object is new in 2.0.0 and there seems no possibility to specify a glob to define files to be deleted now

**Comment by daanvosdewael** [comment]
Take a look at the `cleanOnceBeforeBuildPatterns` option. It's documented in the readme.

**Comment by nitwhiz** [comment]
the _dangerous_ warning made me ignore it. thanks tho.

**Comment by chrisblossom** [comment]
@nitwhiz The warning is there because users can mistakenly remove their project files if they are not careful. FYI, [By default](https://github.com/johnagan/clean-webpack-plugin#about), all files inside webpack's `output.path` are removed before build.

Any ideas how to improve the documentation to show when it is appropriate to configure `cleanOnceBeforeBuildPatterns`, `cleanAfterEveryBuildPatterns` and/or `dangerouslyAllowCleanPatternsOutsideProject` (or any of the other options for that matter)?
