### ISSUE TITLE
2.0.0 error

### ISSUE THREAD

**Issue by ayufeng** [johnagan/clean-webpack-plugin#104]
`new CleanWebpackPlugin(["dist"]),`
version 1.0.1 is ok

**Comment by unguul** [comment]
@ayufeng The configuration options have changed quite a bit with the 2.0.0 release.

While breaking changes are not uncommon with major releases it should have been mentioned in the release notes as a breaking change.

I'm having a similar issue at the moment with the `exclude` option no longer being available.

Will have to revert to v1 for the time being.

**Comment by Sorceror** [comment]
I think it's covered in the comments in the configuration example
```// These options extend del's pattern matching API.
// See https://github.com/sindresorhus/del#patterns
// for pattern matching documentation

// Removes files once prior to Webpack compilation
// Not included in rebuilds (watch mode)
//
// Use !negative patterns to exclude files
 ```
So `!negative` pattern should be the solution. `{ ... , dry: true, ... }`  shows (no need for `verbose` mode) which files will be affected, so it's easy to debug if the selected pattern is correct or not.

**Comment by Sorceror** [comment]
@ayufeng to answer your question. just use `new CleanWebpackPlugin()` and it will do the job, no need to specify anything for webpack's output folder. See the comments for configuration example for details or read the [release notes](https://github.com/johnagan/clean-webpack-plugin/releases/tag/v2.0.0).

**Comment by skipjack** [comment]
Is it to be expected that the actual directory won't be removed in v2? I see the contents of `dist` (in my case) being removed but not the actual directory. Happy to file a separate ticket but wanted to check in first to see what the expected behavior is. This might cause some people to think the plugin isn't working if they don't look inside the directory.

Other than that v2 seems to be working well and it's always nice when less configuration is needed 🎉. Thanks for this plugin!

**Comment by Sorceror** [comment]
I'm not the developer of this plugin, I merely trying to help the others, because I was a bit confused at the beginning (after update) as well.
But, according to this https://github.com/johnagan/clean-webpack-plugin/blob/master/src/clean-webpack-plugin.ts#L272 and to the comment for
```
// Allow clean patterns outside of process.cwd()
//
// requires dry option to be explicitly set
//
// default: false
dangerouslyAllowCleanPatternsOutsideProject: true
```
I would say that deleting the dir is outside the "scope of process.cwd()" hence it's not done by default. You can do it with 
```
new CleanWebpackPlugin({ dry: false, cleanOnceBeforeBuildPatterns: ['**/*', '../dist'], dangerouslyAllowCleanPatternsOutsideProject: true })
``` 
or whatever your output folder is (not tested).

**Comment by chrisblossom** [comment]
@ayufeng the configuration has completely changed with `2.0.0` please read the [README](https://github.com/johnagan/clean-webpack-plugin#usage) and open another issue if you have any further questions. @Sorceror's suggestion to use no configuration should solve your issue. Please provide more details in your next issue so we can provide help.

@unguul @Sorceror pointed out, you should use [negative glob pattern matching](https://github.com/sindresorhus/del#patterns) with either [`cleanOnceBeforeBuildPatterns` and/or `cleanAfterEveryBuildPatterns`](https://github.com/johnagan/clean-webpack-plugin#options-and-defaults-optional) depending on your project's needs.

@skipjack yes that is expected. If you want to remove the entire folder, simply use one of the following configurations: 

- `new CleanWebpackPlugin({ cleanOnceBeforeBuildPatterns: ['**'] })` _[The glob pattern ** matches all children and the parent.](https://github.com/sindresorhus/del#beware)_
- `new CleanWebpackPlugin({ cleanOnceBeforeBuildPatterns: [path.resolve(process.cwd(), 'dist')] })`

@Sorceror Thanks for helping out! FYI, `dangerouslyAllowCleanPatternsOutsideProject` only needs to be used if cleaning outside of [`process.cwd()`](https://nodejs.org/api/process.html#process_process_cwd), not outside of webpack's `output.path`.
