### ISSUE TITLE
v2.0.0 doesn't remove the specified folder

### ISSUE THREAD

**Issue by simonespa** [johnagan/clean-webpack-plugin#105]
When I run webpack with the clean plugin, it doesn't appear to remove the `dist` folder. I'm using

* `clean-webpack-plugin` version 2.0.0
* `webpack` version 4.29.6
* `webpkac-cli` version 3.2.3

and the following is my `webpack.config.js` configuration:

```
{
  .....

  output: {
    filename: 'server.js',
    path: path.resolve(__dirname, 'dist'),
    libraryTarget: 'commonjs2'
  },

  .....

  plugins: [
    new CleanWebpackPlugin({
      cleanOnceBeforeBuildPatterns: ['dist']
    })
  ]
}
```

**Comment by chrisblossom** [comment]
That is because patterns are [relative to webpack's `output.path`](https://github.com/johnagan/clean-webpack-plugin#options-and-defaults-optional). So with that pattern, you are trying to clean `<PROJECT_DIR>/dist/dist/`. Simply remove all configuration and it will work as you expect because the plugin now cleans webpack's `output.path` by default.

**Comment by simonespa** [comment]
Thanks @chrisblossom
