### ISSUE TITLE
It's dosen't work sometimes

### ISSUE THREAD

**Issue by joy-yi0905** [johnagan/clean-webpack-plugin#58]
Thank you for this plugin.

My configuration is like this:

```js
// webpack.config.js
...
var CleanWebpackPlugin = require('clean-webpack-plugin');
...
new CleanWebpackPlugin(
      [
        'dist'
      ]
    )
```

Most of the time you can delete the dist directory.and sometimes the CLI prompt has removed the dist directory, but the dist folder has not actually been removed. I wonder if I have met the same problems as I have.

my work environment following this:

System: window7
Webpack:2.5.1

**Comment by johnagan** [comment]
Is this still happening?

**Comment by NemoStein** [comment]
I've managed to consistently reproduce the problem.
I'm using [http-server](https://github.com/indexzero/http-server) to serve my `dist` folder.
`cmd` and `powershell` locks the directory path, so, when this plugin tries to remove the folder it fails, but doesn't generate any error.
I think a better approach is to remove the contents of the folder instead of removing the folder itself.

**Comment by PacoTiger** [comment]
I am learning webpack and follow the guide about OutManagement. Definitely this clean-webpack-plugin doesn't work the folder dist, but apparently, it runs properly under console without errors notification.

clean-webpack-plugin 0.1.17
webpack 3.6.0

**Comment by PacoTiger** [comment]
I fixed it. Just I added  folder/*.*    where *.* means remove all files inside this folder. You can find more about it in the documentation. It's was very confused and frustrated because the documentation mark it like an option but it's my opinion is strictly needed due to it was the only way the plugin works right to me.

Also I retreive the version webpack 3.5.6

**Comment by simaodeveloper** [comment]
Hello folks, try setup root at the options, thats works for me, because I split the plugins in another file and added it into a sub-folder: 

```javascript
module.exports = function({ path }) {
    
    const plugins = [
        new CleanWebpackPlugin(['dist'], {
            root: path
        }),
        new HtmlWebpackPlugin({
            template: 'src/index.html',
            inject: 'body'
        }),
        new ExtractTextPlugin({
            filename: '[name].[hash].css'
        })
    ];

    return plugins;
}
```

**Comment by mountHouli** [comment]
I'm getting this same problem.  In my case, the `./junk/index.html` file does not get cleaned, but everything else does.

I am certain it is not getting removed (as opposed to me thinking it doesn't get removed but really it's just getting replaced upon rebuild too fast for me to notice) because I checked the created and modified time stamps.

Here's my webpack.config.js

```javascript
module.exports = {
  name: 'client',
  target: 'web',
  entry: {
    clientIndex: path.join(__dirname, 'src', 'clientIndex.js')
  },
  output: {
    filename: './public/[name].bundle.js',
    path: path.join(__dirname, 'dist'),
    publicPath: '/'
  },
  module: {
    rules: [
      {
        test: /\.js(?:x?)$/, // match .js files and .jsx files
        include: [/src/],
        loader: 'babel-loader'
      }
    ]
  },
  resolve: {
    // Make the webpack resolver look for .jsx files (in addition to defaults),
    // so you can import a .jsx file without specifying the extension
    extensions: ['.js', '.json', '.jsx']
  },
  plugins: [
    new CleanWebpackPlugin(
      [
        'dist/*.*',
        'dist/public/*.*',
        'junk/index.html'
      ],
      {
        root: __dirname,
        exclude: '.gitkeep',
        verbose: true
        // set watch: true ??
      }
    ),
    new CopyWebpackPlugin([
      // The "to:" paths are relative to the "output.path:" directory
      {from: 'src/server.js', to: './server.js'},
      {from: 'src/config.js', to: './config.js'}
    ]),
    new HtmlWebpackPlugin({
      template: 'src/index.html.template',
      // The "filename" path is relative to "output.path"
      filename: '../junk/index.html'
    })
  ]
}
```
If I change CleanWebpackPlugin's array of paths to clean from containing `'junk/index.html'` to `'junk/*.html'`, it works.  However, I don't want to delete all .html files in that directory--just `junk/index.html`.

Environment / Versions:
Mac
Node 9.8.0
webpack 3.11.0
clean-webpack-plugin 0.1.19

**Comment by mountHouli** [comment]
BTW, this is its output (notice I have `verbose: true`):
```
clean-webpack-plugin: /Users/houli/docs/gitrepos/camp-trip-client/dist/*.* has been removed.
clean-webpack-plugin: /Users/houli/docs/gitrepos/camp-trip-client/dist/public/*.* has been removed.
clean-webpack-plugin: /Users/houli/docs/gitrepos/camp-trip-client/junk/index.html has been removed.
clean-webpack-plugin: 1 file(s) excluded - .
```

**Comment by joy-yi0905** [comment]
The current version works well!
