### ISSUE TITLE
Problems when using the plugin in Windows

### ISSUE THREAD

**Issue by splincode** [johnagan/clean-webpack-plugin#62]
When I run my builder in TeamCity CI, I get an argument, which directory should be deleted.

- Windows 
 C:\Users\splincode\Git\blackbox/core-adapter-web/target/classes/webapp

- Linux
/home/splincode/Git/blackbox/core-adapter-web/target/classes/webapp

So, the path arrives absolute and I can not know exactly where the script can run from. If I use current configuration, it's work in Linux:

```
var CleanWebpackPlugin = require('clean-webpack-plugin');
var dist = process.env["remove-temporary-folder"];

module.exports = {
  plugins: [
    new CleanWebpackPlugin([dist], {
      root: '/',
      verbose: true
    })
  ]
}

```

But, does not work in Windows, because I need set root as value "C:\/". What should I do to make it cross-platform and work?

**Comment by IllusionMH** [comment]
@splincode You can use `path.resolve('/')` to get root folder (be aware that if you are running node on drive **D:** it will return `'D:\\'` instead of `'C:\\'`).
If this temp folder is inside your working directory - you can just use paths relative to config file (which is usually in the root of the project) and may omit `root` property in options (defaults to `__dirname`)

**Comment by johnagan** [comment]
Did @splincode did @IllusionMH's answer solve your issue?

**Comment by splincode** [comment]
Yes, thank's
