### ISSUE TITLE
Does not respect PowerShell pipe operator

### ISSUE THREAD

**Issue by srmagura** [johnagan/clean-webpack-plugin#87]
Hi, this is a super minor issue but I figured I would post it anyway.

When I run the following command in PowerShell on Windows 10...

    node_modules\.bin\webpack | Out-File $logfile

... I get the following output in the console window

    clean-webpack-plugin: D:\Projects\CapitalCity\CapitalCity\Website\wwwroot\dist has been removed.

All of the webpack output is correctly written to the log file, except the message from clean-webpack-plugin which is written to the console window. The clean-webpack-plugin message should also be written to the log file instead of to the console.

I understand I can disable the clean-webpack-plugin message by setting `verbose=false`.

**Comment by chrisblossom** [comment]
``verbose=false`` uses ``console.warn``, which will output to [``stderr``](https://nodejs.org/api/console.html#console_console_warn_data_args). This was changed to fix https://github.com/johnagan/clean-webpack-plugin/issues/11.

I am unfamiliar with how Windows command line piping works. Try:
``node_modules\.bin\webpack 2>&1 | Out-File $logfile``.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_redirection?view=powershell-6 might be helpful.

**Comment by pshendry** [comment]
Piping passes along only `stdout` output, by design. As @chrisblossom mentioned, that message gets sent to `stderr`, so that explains the behaviour you're seeing. I think something like `2>&1 |` would merge `stderr` into `stdout`, which might be what you're expecting.

I stumbled upon this while trying to figure out why this output goes to `stderr`, so FWIW I'll add one more vote to the "this is confusing" tally. For my use case, setting `verbose=false` for production builds works around it just fine.

**Comment by srmagura** [comment]
Thanks @chrisblossom and @pshendry - that explains it perfectly. Seems like you all are correct to use `console.warn`, but yes, it was a bit confusing. I'll probably just keep `verbose=false` in the future.
